### ISSUE TITLE
Síntesis 

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/sintesis-EDITH-R#2]
[EDITH REYES SANCHEZ - SINTESIS.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-EDITH-R/files/7149019/EDITH.REYES.SANCHEZ.-.SINTESIS.pdf)

**Comment by IvanMc98** [comment]
La síntesis es entendible y contiene las ideas principales acerca del tema.
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
